//HOME_PAGE

// LIST_MOVIE
export const LIST_MOVIE_REQUEST = "ListMovieReducer/LIST_MOVIE_REQUEST";
export const LIST_MOVIE_SUCCESS = "ListMovieReducer/LIST_MOVIE_SUCCESS";
export const LIST_MOVIE_FAILED = "ListMovieReducer/LIST_MOVIE_FAILED";

//LIST_UPCOMING_MOVIE
export const LIST_UPCOMING_MOVIE_REQUEST =
  "ListUpcomingMovieReducer/LIST_UPCOMING_MOVIE_REQUEST";
export const LIST_UPCOMING_MOVIE_SUCCESS =
  "ListUpcomingMovieReducer/LIST_UPCOMING_MOVIE_SUCCESS";
export const LIST_UPCOMING_MOVIE_FAILED =
  "ListUpcomingMovieReducer/LIST_UPCOMING_MOVIE_FAILED";

// MOVIE_DETAILS
export const MOVIE_DETAILS_REQUEST =
  "MovieDetailsReducer/MOVIE_DETAILS_REQUEST";
export const MOVIE_DETAILS_SUCCESS =
  "MovieDetailsReducer/MOVIE_DETAILS_SUCCESS";
export const MOVIE_DETAILS_FAILED = "MovieDetailsReducer/MOVIE_DETAILS_FAILED";

// CINEMA_COMPLEX
export const LIST_CINEMA_SYSTEM_REQUEST =
  "ListCinemaSystemReducer/LIST_CINEMA_SYSTEM_REQUEST";
export const LIST_CINEMA_SYSTEM_SUCCESS =
  "ListCinemaSystemReducer/LIST_CINEMA_SYSTEM_SUCCESS";
export const LIST_CINEMA_SYSTEM_FAILED =
  "ListCinemaSystemReducer/LIST_CINEMA_SYSTEM_FAILED";

export const LIST_CINEMA_REQUEST = "ListCinemaReducer/LIST_CINEMA_REQUEST";
export const LIST_CINEMA_SUCCESS = "ListCinemaReducer/LIST_CINEMA_SUCCESS";
export const LIST_CINEMA_FAILED = "ListCinemaReducer/LIST_CINEMA_FAILED";

// DETAIL_PAGE

// MOVIE_REVIEWS
export const MOVIE_REVIEW_REQUEST = "MovieReviewReducer/MOVIE_REVIEW_REQUEST";
export const MOVIE_REVIEW_SUCCESS = "MovieReviewReducer/MOVIE_REVIEW_SUCCESS";
export const MOVIE_REVIEW_FAILED = "MovieReviewReducer/MOVIE_REVIEW_FAILED";

export const PUT_MOVIE_REVIEW_REQUEST =
  "ChangeMovieReviewReducer/PUT_MOVIE_REVIEW_REQUEST";
export const PUT_MOVIE_REVIEW_SUCCESS =
  "ChangeMovieReviewReducer/PUT_MOVIE_REVIEW_SUCCESS";
export const PUT_MOVIE_REVIEW_FAILED =
  "ChangeMovieReviewReducer/PUT_MOVIE_REVIEW_FAILED";

// LOGIN_PAGE
export const LOGIN_PAGE_REQUEST = "UserLoginReducer/LOGIN_PAGE_REQUEST";
export const LOGIN_PAGE_SUCCESS = "UserLoginReducer/LOGIN_PAGE_SUCCESS";
export const LOGIN_PAGE_FAILED = "UserLoginReducer/LOGIN_PAGE_FAILED";
